export const data = [
  {
    id: 1,
    name: 'Белоголовцев Владимир Сергеевич',
    telegramm: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    register: '01 01 2023',
    status: 'Активный',
    gaidOne: 'Да',
    gaidTwo: 'Нет',
    onboarding: 'Прошёл',
    profile: 'Профиль',
  },
  {
    id: 2,
    name: 'Белоголовцев Владимир Сергеевич',
    telegramm: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    register: '01 01 2023',
    status: 'Активный',
    gaidOne: 'Да',
    gaidTwo: 'Нет',
    onboarding: 'Прошёл',
    profile: 'Профиль',
  },
  {
    id: 3,
    name: 'Белоголовцев Владимир Сергеевич',
    telegramm: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    register: '01 01 2023',
    status: 'Активный',
    gaidOne: 'Да',
    gaidTwo: 'Нет',
    onboarding: 'Прошёл',
    profile: 'Профиль',
  },
];
