export const test = [
  {
    id: 1,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Активный',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Нет',
    onboardingInfo: 'Прошёл',
  },
  {
    id: 2,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Выбыл',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Да',
    onboardingInfo: 'Не прошёл',
  },
  {
    id: 3,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Уточняется',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Нет',
    onboardingInfo: 'Прошёл',
  },
  {
    id: 4,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Активный',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Нет',
    onboardingInfo: 'Прошёл',
  },
  {
    id: 5,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Выбыл',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Да',
    onboardingInfo: 'Не прошёл',
  },
  {
    id: 6,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Уточняется',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Нет',
    onboardingInfo: 'Прошёл',
  },
  {
    id: 7,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Активный',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Нет',
    onboardingInfo: 'Прошёл',
  },
  {
    id: 8,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Выбыл',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Да',
    onboardingInfo: 'Не прошёл',
  },
  {
    id: 9,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Уточняется',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Нет',
    onboardingInfo: 'Прошёл',
  },
  {
    id: 10,
    fio: 'Белоголовцев Владимир Сергеевич',
    telegram: '@way26ru',
    promo: 'VLAD01',
    city: 'Москва',
    course: 'ДИ',
    registrationDate: '01 01 2023',
    status: 'Уточняется',
    guideOneInfo: 'Да',
    guideTwoInfo: 'Нет',
    onboardingInfo: 'Прошёл',
  },
];
